# vim:fileencoding=utf-8:foldmethod=marker
# TMUX Config

setw -g mode-keys vi # Use vi keybindings in copy mode
set -g mouse on # Enable mouse support

# use vim-like keys for splits and windows
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
