# vim:fileencoding=utf-8:foldmethod=marker
# TMUX Config

setw -g mode-keys vi # Use vi keybindings in copy mode
set -g mouse on # Enable mouse support

# Vim Keys for selecting panes.
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Remove prompts when deleting panes and windows.
bind-key & kill-window
bind-key x kill-pane
