# vim:fileencoding=utf-8:foldmethod=marker
# TMUX Config

# Options {{{1
set -g default-terminal "screen-256color" # Set default terminal type.
# set -g mouse on # Enable mouse support.
setw -g mode-keys vi # Use vi keybindings in copy mode.
set -g base-index 1 # Start window incexing at 1.
setw -g pane-base-index 1 # Start window incexing at 1.
set-option -sg escape-time 0 # Time to wait for escape sequence.
set -g set-clipboard on # Use system clipboard.

# Binds {{{1
bind-key & kill-window # Remove prompts when deleting windows.
bind-key x kill-pane # Remove prompts when deleting panes.

# Vim Keys for selecting panes.
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
