"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "CubeSeal"
email = "kenndesilva1@gmail.com"

[signing]
behavior = "drop"
backend = "ssh"
key = "~/.ssh/id_ed25519-singing.pub"

[git]
sign-on-push = true
